const biology = [
  {label: "Chemistry in Biology", name: "ChemistryinBiology"},
  {label: "Macromolecules", name: "Macromolecules"},
  {label: "Carbohydrates", name: "Carbohydrates"},
  {label: "Lipids", name: "Lipids"},
  {label: "Proteins", name: "Proteins"},
  {label: "Nucleic acids", name: "Nucleicacids"},
  {label: "Diffusion and osmosis", name: "Diffusionandosmosis"},
  {label: "Homeostasis", name: "Homeostasis"},
  {label: "Water and electrolyte balance", name: "Waterandelectrolytebalance"},
  {label: "Energy and metabolism", name: "Energyandmetabolism"},
  {label: "Cell biology", name: "Cellbiology"},
  {label: "Prokaryotes, Bacteria & Archaea", name: "Prokaryotes,Bacteria&Archaea"},
  {label: "Eukaryotes", name: "Eukaryotes"},
  {label: "Cells", name: "Cells"},
  {label: "Cell membrane", name: "Cellmembrane"},
  {label: "Organelles", name: "Organelles"},
  {label: "Nucleus", name: "Nucleus"},
  {label: "DNA", name: "DNA"},
  {label: "RNA", name: "RNA"},
  {label: "mRNA", name: "mRNA"},
  {label: "tRNA", name: "tRNA"},
  {label: "rRNA", name: "rRNA"},
  {label: "Riboosmes", name: "Riboosmes"},
  {label: "Lysosomes", name: "Lysosomes"},
  {label: "Endoplasmic Reticulum", name: "EndoplasmicReticulum"},
  {label: "Golgi Apparatus", name: "GolgiApparatus"},
  {label: "Mitochondria", name: "Mitochondria"},
  {label: "Cellular respiration", name: "Cellularrespiration"},
  {label: "mtDNA", name: "mtDNA"},
  {label: "Chloroplasts", name: "Chloroplasts"},
  {label: "Photosynthesis", name: "Photosynthesis"},
  {label: "plastome, cpDNA", name: "plastome,cpDNA"},
  {label: "Vacuoles", name: "Vacuoles"},
  {label: "Cell Division and Reproduction", name: "CellDivisionandReproduction"},
  {label: "Binary Fission/Mitosis", name: "BinaryFission/Mitosis"},
  {label: "Meiosis", name: "Meiosis"},
  {label: "Metabolism", name: "Metabolism"},
  {label: "Metabolic pathways", name: "Metabolicpathways"},
  {label: "Cell signalling", name: "Cellsignalling"},
  {label: "Receptors", name: "Receptors"},
  {label: "Signalling pathways", name: "Signallingpathways"},
  {label: "Gene regulation", name: "Generegulation"},
  {label: "Transcription factors", name: "Transcriptionfactors"},
  {label: "Epigenetic", name: "Epigenetic"},
  {label: "DNA modifications", name: "DNAmodifications"},
  {label: "RNA interference", name: "RNAinterference"},
  {label: "Virology", name: "Virology"},
  {label: "Immunology", name: "Immunology"},
  {label: "Evolution", name: "Evolution"},
  {label: "Mendel and Darwin", name: "MendelandDarwin"},
  {label: "Punnet Squares", name: "PunnetSquares"},
  {label: "Population genetics", name: "Populationgenetics"},
  {label: "Taxonomy", name: "Taxonomy"},
  {label: "Botany", name: "Botany"},
  {label: "Zoology", name: "Zoology"},
  {label: "Ecology", name: "Ecology"},
  {label: "Ecosystem", name: "Ecosystem"},
  {label: "Biodiversity", name: "Biodiversity"},
  {label: "Habitat, Niche, Biotope, Environment", name: "Habitat,Niche,Biotope,Environment"},
  {label: "Vegetation", name: "Vegetation"},
  {label: "Paleontology", name: "Paleontology"}
]
export default biology;