
const  computerscience =  [
  {label: "Boolean logic", name: "Booleanlogic"},
  {label: "Systems architecture", name: "Systemsarchitecture"},
  {label: "Memory and storage", name: "Memoryandstorage"},
  {label: "Hardware", name: "Hardware"},
  {label: "Software", name: "Software"},
  {label: "Operating systems", name: "Operatingsystems"},
  {label: "High- and low-level languages", name: "High-andlow-levellanguages"},
  {label: "Translators", name: "Translators"},
  {label: "Data structures", name: "Datastructures"},
  {label: "Searching algorithms", name: "Searchingalgorithms"},
  {label: "Sorting algorithms", name: "Sortingalgorithms"},
  {label: "Pathfinding algorithms", name: "Pathfindingalgorithms"},
  {label: "Complexity", name: "Complexity"},
  {label: "Computer networks", name: "Computernetworks"},
  {label: "Network fundamentals", name: "Networkfundamentals"},
  {label: "The internet", name: "Theinternet"},
  {label: "Network hardware", name: "Networkhardware"},
  {label: "Communication", name: "Communication"},
  {label: "Web technologies", name: "Webtechnologies"},
  {label: "Number systems and sets", name: "Numbersystemsandsets"},
  {label: "Mathematical functions", name: "Mathematicalfunctions"},
  {label: "Programming concepts", name: "Programmingconcepts"},
  {label: "String handling", name: "Stringhandling"},
  {label: "Subroutines", name: "Subroutines"},
  {label: "File handling", name: "Filehandling"},
  {label: "Recursion", name: "Recursion"},
  {label: "Procedural programming", name: "Proceduralprogramming"},
  {label: "Object-oriented programming", name: "Object-orientedprogramming"},
  {label: "Functional programming", name: "Functionalprogramming"},
  {label: "Event-driven programming", name: "Event-drivenprogramming"},
  {label: "Data and information", name: "Dataandinformation"},
  {label: "Representation of numbers", name: "Representationofnumbers"},
  {label: "Representation of text", name: "Representationoftext"},
  {label: "Representation of images", name: "Representationofimages"},
  {label: "Representation of sound", name: "Representationofsound"},
  {label: "Compression", name: "Compression"},
  {label: "Encryption", name: "Encryption"},
  {label: "Database concepts", name: "Databaseconcepts"},
  {label: "SQL", name: "SQL"},
  {label: "Big Data", name: "BigData"},
  {label: "Program design", name: "Programdesign"},
  {label: "Testing", name: "Testing"},
  {label: "Software engineering principles", name: "Softwareengineeringprinciples"},
  {label: "A level programming project / NEA", name: "Alevelprogrammingproject/NEA"}
]

export default computerscience;