const indianHistory = [
{label: "Prehistoric era (until c. 3300 BCE)", name: "Prehistoricera(untilc.3300BCE)"},
{label: "Paleolithic", name: "Paleolithic"},
{label: "Neolithic", name: "Neolithic"},
{label: "Bronze Age – first urbanisation", name: "BronzeAge–firsturbanisation(c.3300–c.1800BCE)"},
{label: "Indus Valley Civilisation", name: "IndusValleyCivilisation"},
{label: "Ochre Coloured Pottery Culture", name: "OchreColouredPotteryCulture"},
{label: "Iron Age (1500 – 200 BCE)", name: "IronAge(1500–200BCE)"},
{label: "Vedic period (c. 1500 – 600 BCE)", name: "Vedicperiod(c.1500–600BCE)"},
{label: "Second urbanisation (600–200 BCE)", name: "Secondurbanisation(600–200BCE)"},
{label: "Classical and early medieval periods (c. 200 BCE – c. 1200 CE)", name: "Classicalandearlymedievalperiods(c.200BCE–c.1200CE)"},
{label: "Early classical period (c. 200 BCE – c. 320 CE)", name: "Earlyclassicalperiod(c.200BCE–c.320CE)"},
{label: "Classical period: Gupta Empire (c. 320 – 650 CE)", name: "Classicalperiod:GuptaEmpire(c.320–650CE)"},
{label: "Early medieval period (mid 6th c.–1200 CE)", name: "Earlymedievalperiod(mid6thc.–1200CE)"},
{label: "Late medieval period (c. 1200–1526 CE)", name: "Latemedievalperiod(c.1200–1526CE)"},
{label: "Delhi Sultanate", name: "DelhiSultanate"},
{label: "Vijayanagara Empire", name: "VijayanagaraEmpire"},
{label: "Mewar Dynasty (728-1947)", name: "MewarDynasty(728-1947)"},
{label: "Early modern period (c. 1526–1858 CE)", name: "Earlymodernperiod(c.1526–1858CE)"},
{label: "Mughal Empire", name: "MughalEmpire"},
{label: "Marathas and Sikhs", name: "MarathasandSikhs"},
{label: "European exploration", name: "Europeanexploration"},
{label: "East India Company rule in India", name: "EastIndiaCompanyruleinIndia"},
{label: "Modern period and independence (after c. 1850 CE)", name: "Modernperiodandindependence(afterc.1850CE)"},
{label: "Rebellion of 1857 and its consequences", name: "Rebellionof1857anditsconsequences"},
{label: "British Raj (1858–1947)", name: "BritishRaj(1858–1947)"},
{label: "Indian independence movement (1885–1947)", name: "Indianindependencemovement(1885–1947)"},
{label: "Independence and partition (c. 1947–present)", name: "Independenceandpartition(c.1947–present)"}
]

export default indianHistory;