const physics= [
    {label: "SIUnits", name: "SIUnits"},
    {label: "Scalar (physics)", name: "Scalar(physics)"},
    {label: "Euclidean vector", name: "Euclideanvector"},
    {label: "Motion graphs and derivatives", name: "Motiongraphsandderivatives"},
    {label: "Pythagorean theorem", name: "Pythagoreantheorem"},
    {label: "Trigonometry", name: "Trigonometry"},
    {label: "Motion", name: "Motion"},
    {label: "Force", name: "Force"},
    {label: "Linear motion", name: "Linearmotion"},
    {label: "Displacement", name: "Displacement"},
    {label: "Speed", name: "Speed"},
    {label: "Velocity", name: "Velocity"},
    {label: "Acceleration", name: "Acceleration"},
    {label: "Center of mass", name: "Centerofmass"},
    {label: "Mass", name: "Mass"},
    {label: "Momentum", name: "Momentum"},
    {label: "Newtons laws of motion", name: "Newtonslawsofmotion"},
    {label: "Work (physics)", name: "Work(physics)"},
    {label: "Free body diagram", name: "Freebodydiagram"},
    {label: "Angular acceleration", name: "Angularacceleration"},
    {label: "Angular momentum (Introduction)", name: "Angularmomentum(Introduction)"},
    {label: "Angular velocity", name: "Angularvelocity"},
    {label: "Centrifugal force", name: "Centrifugalforce"},
    {label: "Centripetal force", name: "Centripetalforce"},
    {label: "Circular motion", name: "Circularmotion"},
    {label: "Tangential velocity", name: "Tangentialvelocity"},
    {label: "Torque", name: "Torque"},
    {label: "Energy", name: "Energy"},
    {label: "Conservation of energy", name: "Conservationofenergy"},
    {label: "Elastic collision", name: "Elasticcollision"},
    {label: "Inelastic collision", name: "Inelasticcollision"},
    {label: "Inertia", name: "Inertia"},
    {label: "Moment of inertia", name: "Momentofinertia"},
    {label: "Momentum", name: "Momentum"},
    {label: "Kinetic energy", name: "Kineticenergy"},
    {label: "Potential energy", name: "Potentialenergy"},
    {label: "Rotational energy", name: "Rotationalenergy"},
    {label: "Ampères circuital law", name: "Ampèrescircuitallaw"},
    {label: "Capacitor", name: "Capacitor"},
    {label: "Coulombs law", name: "Coulombslaw"},
    {label: "Diode", name: "Diode"},
    {label: "Direct current", name: "Directcurrent"},
    {label: "Electric charge", name: "Electriccharge"},
    {label: "Electric current", name: "Electriccurrent"},
    {label: "Alternating current", name: "Alternatingcurrent"},
    {label: "Electric field", name: "Electricfield"},
    {label: "Electric potential energy", name: "Electricpotentialenergy"},
    {label: "Electron", name: "Electron"},
    {label: "Faradays law of induction", name: "Faradayslawofinduction"},
    {label: "Ion", name: "Ion"},
    {label: "Inductor", name: "Inductor"},
    {label: "Joule heating", name: "Jouleheating"},
    {label: "Lenzs law", name: "Lenzslaw"},
    {label: "Magnetic field", name: "Magneticfield"},
    {label: "Ohms law", name: "Ohmslaw"},
    {label: "Resistor", name: "Resistor"},
    {label: "Transistor", name: "Transistor"},
    {label: "Transformer", name: "Transformer"},
    {label: "Voltage", name: "Voltage"},
    {label: "Entropy", name: "Entropy"},
    {label: "First law of thermodynamics", name: "Firstlawofthermodynamics"},
    {label: "Heat", name: "Heat"},
    {label: "Heat transfer", name: "Heattransfer"},
    {label: "Second law of thermodynamics", name: "Secondlawofthermodynamics"},
    {label: "Temperature", name: "Temperature"},
    {label: "Thermal energy", name: "Thermalenergy"},
    {label: "Thermodynamic cycle", name: "Thermodynamiccycle"},
    {label: "Volume (thermodynamics)", name: "Volume(thermodynamics)"},
    {label: "Work (thermodynamics)", name: "Work(thermodynamics)"},
    {label: "Wave", name: "Wave"},
    {label: "Longitudinal wave", name: "Longitudinalwave"},
    {label: "Transverse waves", name: "Transversewaves"},
    {label: "Transverse wave", name: "Transversewave"},
    {label: "Standing Waves", name: "StandingWaves"},
    {label: "Wavelength", name: "Wavelength"},
    {label: "Frequency", name: "Frequency"},
    {label: "Light", name: "Light"},
    {label: "Light ray", name: "Lightray"},
    {label: "Speed of light", name: "Speedoflight"},
    {label: "Sound", name: "Sound"},
    {label: "Speed of sound", name: "Speedofsound"},
    {label: "Radio waves", name: "Radiowaves"},
    {label: "Harmonic oscillator", name: "Harmonicoscillator"},
    {label: "Hookes law", name: "Hookeslaw"},
    {label: "Reflection", name: "Reflection"},
    {label: "Refraction", name: "Refraction"},
    {label: "Snells law", name: "Snellslaw"},
    {label: "Refractive index", name: "Refractiveindex"},
    {label: "Total internal reflection", name: "Totalinternalreflection"},
    {label: "Diffraction", name: "Diffraction"},
    {label: "Interference (wave propagation)", name: "Interference(wavepropagation)"},
    {label: "Polarization (waves)", name: "Polarization(waves)"},
    {label: "Vibrating string", name: "Vibratingstring"},
    {label: "Doppler effect", name: "Dopplereffect"},
    {label: "Gravity", name: "Gravity"},
    {label: "Gravitational potential", name: "Gravitationalpotential"},
    {label: "Newtons law of universal gravitation", name: "Newtonslawofuniversalgravitation"},
    {label: "Universal Gravitational Constant", name: "UniversalGravitationalConstant"}
  ]

  export default physics;